namespace Conway.App.Raylib

open Conway.Core

module Preset =
    let presetOne =
        let innerArray = [|
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.living
                Cell.dead
                Cell.living
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.living
                Cell.dead
                Cell.living
                Cell.dead
                Cell.living
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.living
                Cell.dead
                Cell.living
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
        |]

        let innerPreset row col = innerArray[row][col]

        21, 21, innerPreset

    let deadPreset =
        let innerArray = [|
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
            [|
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
                Cell.dead
            |]
        |]

        let innerPreset row col = innerArray[row][col]

        21, 21, innerPreset
