namespace Conway.App

open Conway.Core

module Preset =
    let presetOne =
        let innerArray = [|
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                1<CellStatus>
                0<CellStatus>
                1<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                1<CellStatus>
                0<CellStatus>
                1<CellStatus>
                0<CellStatus>
                1<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                1<CellStatus>
                0<CellStatus>
                1<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
        |]

        let innerPreset row col = innerArray[row][col]

        21, 21, innerPreset

    let deadPreset =
        let innerArray = [|
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
            [|
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
                0<CellStatus>
            |]
        |]

        let innerPreset row col = innerArray[row][col]

        21, 21, innerPreset
