name: .NET AOT Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish Linux (AOT)
        run: dotnet publish \
              ./src/Conway.App/ \
              -c Release \
              -r linux-x64 \
              -p:PublishAot=true \
              -p:AssemblyName=ConwaysGameOfLife \
              --self-contained true \
              -o ./linux-build/ConwaysGameOfLife

      - name: Archive Linux build
        run: zip -r linux-x64.zip ./linux-build/ConwaysGameOfLife

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: linux-x64.zip

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish Windows (AOT)
        run: dotnet publish \
              ./src/Conway.App/\
              -c Release \
              -r win-x64 \
              -p:PublishAot=true \
              -p:AssemblyName=ConwaysGameOfLife \
              --self-contained true \
              -o ./windows-build/ConwaysGameOfLife

      - name: Archive Windows build
        run: powershell Compress-Archive -Path ./windows-build/ConwaysGameOfLife -DestinationPath ./win-x64.zip

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-x64
          path: win-x64.zip

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [build-linux, build-windows]
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-x64
          path: ./

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: win-x64
          path: ./

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            linux-x64.zip
            win-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}